hash-format = "sha256"

[[files]]
file = "config/NoChatReports/NCR-Client.json"
hash = "32dc5f1d73b05e70f3fc5a18f58c5d81a095484a0f93a1da6d1883966ff4e296"

[[files]]
file = "config/badoptimizations.txt"
hash = "a47ef2a99eee3632074b8c2869e1ce3182f7348eaf916a2045e06b2a47e58cd4"

[[files]]
file = "config/cape-provider.json5"
hash = "6b65e1270f555a74560a10fa17bb6b7290e022f46dc02b29239b32a1b3d27b37"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "3817e94107bb1c7358beebb80b1810e822de38be430f855cf14828c38018e8e2"

[[files]]
file = "config/immediatelyfast.json"
hash = "eb455656c3e3e8effa1e9c085b96894b469aa545807e3f621dde74a1c3a0833f"

[[files]]
file = "config/iris.properties"
hash = "4b404c16b82563e05e0cc8dc1218eb6194b2aa4473f348ff0c0c7a8655d9b5ff"

[[files]]
file = "config/litematica.json"
hash = "68322256c1240f38496d80e3e6df017a936cec6d9d965b7f815a4966c5873f5d"

[[files]]
file = "config/malilib.json"
hash = "c7acba3f6019a96750b90508685939ab0801876a9d6f40475e9310eb05d620ed"

[[files]]
file = "config/modernfix-mixins.properties"
hash = "e46272cc1db3b1f8c7d6bdc0c89d0b2e336a8d30ad0081e645f76c427be3cbec"

[[files]]
file = "config/moreculling.toml"
hash = "47c90ca85fa6733e7b4fb652760b91506957ae19a830c02caa72d20df405819a"

[[files]]
file = "config/puzzle.json"
hash = "9ef4deb1dee36af524dd6c6664c9ae36934639c0384b232c1109d1fd92becba9"

[[files]]
file = "config/sodium-extra-options.json"
hash = "e3927c55ce0508a6328e373e1811191836fe56933f73d1fb320a1df21154081d"

[[files]]
file = "config/sodium-options.json"
hash = "5358a572a26d8008c6c49e00ab3a0fe65dd89761cb86a235496900b587b9526c"

[[files]]
file = "config/vmp.properties"
hash = "0d0549563aca08c87a22a9fd862cc6e7a9906f2d6fca84dcbfa7cbec14dff7e6"

[[files]]
file = "config/xaerominimap.txt"
hash = "8627b3553cbc1ae4e5556e7132991abc45d5a7b604f593e75f1389091278e0a5"

[[files]]
file = "config/xaeroplus.txt"
hash = "8b400926fa2c106000afe3609286259d69491bd725ca2dc7d0a27a3d9ea6dd08"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "abdb3661a1864dffbbdb7e5ba71a64fcb6c68b779dd4cc5d6dee41825e45abde"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "0b0a73afb2fbe5df2ac6632141e1dc94a5d2f03e53614418155adff2b64d6210"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "bc0b2d242970a527d672fa2e09fb98828bf84dff97bc30d2614d74189ed49c9a"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea4c8757cbc72739729f878472768d0d07cde302c8f5292014e88a299d5bad31"
metafile = true

[[files]]
file = "mods/armor-stand-arms.pw.toml"
hash = "1a418303bce43e347e68a79d7b12caa62e20945c762874c6f5d3359f45705538"
metafile = true

[[files]]
file = "mods/axolotl-buckets.pw.toml"
hash = "6140f1186fe78803916207e5e6149e4920361c68d1f1eafe989e7afb4a2826a5"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "8c74c1387d413eb57b880859a5c160ae751b23dc0d75cee1bf6b287ff267cf37"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
hash = "a4dfb048fd33957abf61c726c3d0d8a0d5c47e06fe06a100f4bbc64bd99014b2"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "39cd5af4547f7951b7bbaee014a93626d11d1d563271a82efd562f057125ff8a"
metafile = true

[[files]]
file = "mods/bl4cks-sit.pw.toml"
hash = "a73ccfaf1347a2597d818aa6eed5cfe80d3c54b1d946cfef3851203e1de34796"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "201814b124dccbec493f99385c62261425803460818f4565bd1b9276f1a8f516"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "d6878871a07870b33821beed20118368e779c17574062d5d771eb38b9403e875"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "6b58736320004020868beee139c31e5cf2211b93163db99acbaf6c71fd2835b9"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "abc387a020c7ed360eae2841609ad0a69f0df06c668fbb27776e232bbc1c30d9"
metafile = true

[[files]]
file = "mods/cave-dust.pw.toml"
hash = "177b482b2fa380214799c4edd086d2b9155ac076a62497ed6d38bf722b0fd708"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "6f4c01dc2a28a2c74ccdd5ba7f5566d6302a6e4e994edb01ed9cd1eba701c1ed"
metafile = true

[[files]]
file = "mods/chatanimation.pw.toml"
hash = "a59ce679862d915b6a8bdfe207af78012214fb5a6952e0663eb07c98d7c88793"
metafile = true

[[files]]
file = "mods/cherished-worlds.pw.toml"
hash = "2421ac237c161c3eabebb1416d661f90560f17b24a7679dae4098026a9a44619"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "9a449ab2f0bf9220a3e83c734f8c76f9391c9bcabc0f223593b9dec4dbf1d388"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
hash = "746f70bb8de0233b9775ff2092e7294854937f724122f54ec09a5a7005e716bc"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "1d3d810fb49f6b74078abfb8aa2816715cc2840ba6324c9fcabff984b9b72412"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "6468d59593c684cefdadd5c6f3f15959afe71bceb772f690374cac66c111a221"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "cd4d0c2db8c45235322fb097de824765c2e9ef1a762f8870b08680b92b8cede0"
metafile = true

[[files]]
file = "mods/coolrain.pw.toml"
hash = "61cafe4f872977ccd2c726a66370b42fb675d8ef2cacc33bd7800ca1e5636ef3"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
hash = "9e80eddada6a04b2a831ebe5a47acced7464cec2b2fddfe5a08fc5a828e52fea"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "60eab6ec5f29fc035ece627513e61cdacebcba6a7f7c0406ce977c802832e865"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "7a4c84bff6bbde748c83f918777500866931b690ae5e9e126c0452fd295c9616"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
hash = "faca62babb2eb5104279b4a55cb4066b8f111989e8dc2575826b162668c2a1fd"
metafile = true

[[files]]
file = "mods/dripsounds.pw.toml"
hash = "518180314697dadfd8a159a53fd9ab37d8cf54092086e913eae45f5fd7603af4"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "9eadb937c438421e85a21338153114f97c75ab3dd6f3a49305bc8d0d7b3688aa"
metafile = true

[[files]]
file = "mods/elytra-trims.pw.toml"
hash = "03a2b9701d7df9c1662cd1e1fc3fc234a0de9e6dd5df6672eb0cd05dc05b526c"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "d52f28f30e140f0803d1827bc511445af3e270a326fe3f3316ed319d1b6aaea2"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "8150d32c94dc392e2048adc3c1bfddea0b7531fb640f19a7fa7b0c73971de739"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "fa48dbbd4792173062bf7f3e66387530edf4bbd12b574be039d0e29992fd60f5"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "601b7c64b8186d1c61a1cb12cde0c016fbe40fe48fa4a82019efc448a8231d6b"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "32ba5b383cc4307b7728d46ae92a5e0ba82c2cbf4924955c19824f2a2c79da8b"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "d88352f607700aed0db6a0679d4a2a2eaba2a83d38696ca966c2dace0a32f2b7"
metafile = true

[[files]]
file = "mods/forcecloseworldloadingscreen.pw.toml"
hash = "d80049f4f9438f229920965bfbd1354a23165747a1f84e9b39ab8333bce527c5"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "0a9e8b5a91691fbe801664a397c854017ac1abc3b348bf5214c39ecacc33c4ce"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "d213dc35ec09b56dcf792c1ecc557c81ecd9fb099d19412bef25c2e4974af2d7"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "86f3bf44d767d1b1a1e76e6db5bd99e757875daeb3f9a4ac2afef86d2b020151"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "c3d4f2627461782145554911f6f5e79d91d25cb1cdfc2c7386769cf3b9c7b97f"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "cb85864ff2d3936a5ab4f7e7ccf763dbda0153412ba52c95a63b29677a012aaf"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "7bd338427b6cb8fec3c4a1af53ab186ba3b179674f272385573bc5d946fd1115"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "aedaac031578bcfcf9cd635d88b778304e11f893864e4cbfbddb67a8c8e34c14"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "ae7a92019f93189086a4d3d5fa5ead6b835bcc651bbb8b1a86a618d9c34738fd"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "11b5313f860f439d86b64140ffd75f1aa519c2b048ced21aaedaaa2d347c1688"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
hash = "d667e14ba3e1a4006583fc3fe202f8291525b20b400c23ce5d9b71fb6d71ea5e"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "0373144a94990dbb3f9c3e0006e3b5a787c51dda2b86a02e1fa61efed9772951"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "8ee12811c34ff12dfbeb54851b33430ed624b3e06daead3a9bd57db6d8ff3878"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "2ba33ca127dd515c1e63c0166ae52884f3e8ecca89c14278d1758882fc2fc126"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
hash = "f531a8ee70e9d78ee62a84e3fd18088070dcf8f2cee2384a8aabed16dbfafe6c"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "101ebcfba78e83448379c1388f7030bd5ee18de45219e0654425c53962a0a824"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "38ab12bf19d6cafd9208c4715a84cbfc1606af625f9fce9e253fed8251eaf506"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "06d0708b2f778731f7520021f2f3c2284a347fd6679f0227e97fea4140b374a8"
metafile = true

[[files]]
file = "mods/naturally-trimmed.pw.toml"
hash = "ac0273eec7d0823d9c8a214f68728a80a32082e087f27aa1799a043ed54617ec"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "7109df72174bc3fe15d9f5435767d63c69cb03b49910095618bd80888af08240"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "150cbda6112791a4db5f3591482256cbd12f9c146008f8f6130cc51fed23bb80"
metafile = true

[[files]]
file = "mods/nuit-interop.pw.toml"
hash = "bc1e9aadb3118b7835eb12bbeb1d9fa089114e0b703543aa93af7e8db1e7527b"
metafile = true

[[files]]
file = "mods/nuit.pw.toml"
hash = "0fa17f36e80b3c8417be0070ab44358b1aa06b513f76975110841014513504f0"
metafile = true

[[files]]
file = "mods/obsidianui.pw.toml"
hash = "4aeeec36ae800bcda13f61688ed82396f532e9ed6421daf9b45e997770fd03db"
metafile = true

[[files]]
file = "mods/optiboxes.pw.toml"
hash = "b5cb84815833d2b87d74c5056428ccb267ec68216495022041a799f9b85c6d07"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "36f49439d20a738ab3ad5edacca9240f82492b91fd168a23e943505d75777bbf"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "f0baa8708ef16855f5bb5ad67578e67a003201331702d54bd4d84b25fb529a61"
metafile = true

[[files]]
file = "mods/pickup-notifications.pw.toml"
hash = "fd2f72ea433017cad5f2ca4cd4f390d775eb0950ebb15d5ea23674a9f5d51ac0"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "fbdf5f9010d5f83277f4cdd30d33ced05fa1f7db2b3dad9cdaf114ee99f7d8db"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "dc6a3bb89fbc1455fb8cb87bc2518f5a9cb6d8e483d87d302b808bc6188d55c3"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "3f0788aedf032f4a7e8c1c5684e35cc4c3070205f50137144d7526dd45120633"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "153de543c638f8766ec42562f9ac98f22dc6e8138d0f70c17260f3dde9797d4c"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "732ab3742d45e5d90961b24b83b94aeb13928a8faac96f714568e01984f26bef"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "5cd85b655ab6f76b25205aa10ca5bc355b96f4e43d041a75907aa528f0dbd96f"
metafile = true

[[files]]
file = "mods/ryoamiclights.pw.toml"
hash = "cbe391a837a3dc2e294760aef5afeaefec3fba9e237b1fcdda481983aca00e07"
metafile = true

[[files]]
file = "mods/serverpingerfixer.pw.toml"
hash = "480117bbfe84aa4d902cd1f45053ed4df0738f12daf163d83436e5a1ac2804e2"
metafile = true

[[files]]
file = "mods/smooth-scroll.pw.toml"
hash = "d54bc85ebdfca5e2cc2584226184ddce8f092b37af6e6abf43cc0b039045af32"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "b61ab82e0128ac072934bc4f10a76d134e3f01c8ee1f41f5e8f1b7c1a2b59f1a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "8db240d22fb9eb721449d55de72420a951edfca51d94090fa7db3d3a35c6002f"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "fa78ade5b969563d9d3fcd625cf53a748c76c45b4965a4c435f7008beedf757f"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
hash = "10b12cf73a63a0fb82d769cef78ba6fd6e91d360a3d53b8059e2ba90fcd2bbb4"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "a3cd1621ec8a4bbf17a634ceefd320dad0d9f2d7ed8d6af1a8bd982ced15d179"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "f855b2a82e8da1e2834a32616cbe5097c2e52411d42df4fde6b3636cd3465937"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "3b61fcf1c80cfdd79282be71ddfa9cce02fc13f8d87a760db455e2a97b801f40"
metafile = true

[[files]]
file = "mods/text-formatting-everywhere.pw.toml"
hash = "7e08e4f76649a2fba00bb6eae7b59af18513c01140b50cd94299c70232c597c9"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
hash = "cb023cd1609445fe5f515fedc9de3b670b05b59f66af2ee43520705c70669489"
metafile = true

[[files]]
file = "mods/villager-names-serilum.pw.toml"
hash = "7ea67f33055801b986a1ece4421f2d227131f41293306077d15afad064ef174d"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "dc67a6b542afb8c9d927c3e1717e313964f03329f4081c65ea93525d44bac76e"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "7cc9c5d9023fe57e3a4ee684abdd56d9dc21e503d59e2611cde6e791b5b95b3f"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "6acec6ef071f590a5ab59ff758069042ca5bc3c870947539f2c2d11d724faf2d"
metafile = true

[[files]]
file = "mods/xaeroplus.pw.toml"
hash = "8bc946deb4f8ca082d8badc21b62d0bea2df801ec49e3fee46b62f45eea9be2e"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "08874012fad6f8189c5d810f97f562516749b86123e71a1e243b4bebc1943c35"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "cf4a5533e10d02edfdc2c44ba79d91ccdd7cd46e7205b808a55105c32aeb3dfa"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "68442472ca2278558495f58d9d155b301cb05bdf0b64717a8d0a502a99b69cb1"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "48a6c4ebdc22d4ed7a3168d578adffb0ce25cf1130327bcbbe050384460eb76a"
metafile = true

[[files]]
file = "options.txt"
hash = "1ad11db31f44bee821bae9bfa030cf06396007c17be4695dfd69ef849e8a3571"

[[files]]
file = "resourcepacks/3d-ladders.pw.toml"
hash = "e2b2a4efae8ee22c811a54c2eea8f593c11444e673036353ba972c6cd104f397"
metafile = true

[[files]]
file = "resourcepacks/better-lanterns.pw.toml"
hash = "c72c4abb983e9c87f2b632dbe43b2ded33cc5d59987a80b2029492d31f534bb8"
metafile = true

[[files]]
file = "resourcepacks/chat-reporting-helper.pw.toml"
hash = "b33036850e44c6a79c3995027144a1758ca16e0f46c36bc068870575e2f4fe26"
metafile = true

[[files]]
file = "resourcepacks/drodis-blazes-x-fresh-animations.pw.toml"
hash = "df3860935e4d3a6aa0bd3a7aa1aa6e9d0703204db231a37f60f983bfe0ed05f7"
metafile = true

[[files]]
file = "resourcepacks/enchant-icons-countxd.pw.toml"
hash = "8f91821261e292f61e7facdd05bb4272f8eff1fa82145f82b1e47a44e809a045"
metafile = true

[[files]]
file = "resourcepacks/enchanted-books-re-covered.pw.toml"
hash = "f02b95d21e78b75d1a1c93296e1dd90dc5d03439958fd1596cb77bbce864663f"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "b843c282f94af79a4970c91879eff4073932409aa045b722b48054bd4b2fd45d"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "bf6bf356ece200c132c604c1cdd981c8a7baf6a30ed05fa057fdfc0444df779d"
metafile = true

[[files]]
file = "resourcepacks/fresh-flower-pots.pw.toml"
hash = "6ea70716dbbdddf6bdbeb137208a38380159048813accecb225ca6d19ce37e97"
metafile = true

[[files]]
file = "resourcepacks/gentler-weather-sounds.pw.toml"
hash = "9164c7d742c4e3272081c48a9559b00a16c918ce7ed27857a252fc7db18d3cdd"
metafile = true

[[files]]
file = "resourcepacks/human-era-villagers-illagers.pw.toml"
hash = "c3a40eb78034c9c013928db9a02a814070d8041e9648c8bd7b5fefbd5f5ba9ef"
metafile = true

[[files]]
file = "resourcepacks/rays-3d-rails.pw.toml"
hash = "0e80f97855da0ee8b2cba02d4cc1f3c82f50bd1ec0772645cfd5dd5d6f4e9a86"
metafile = true

[[files]]
file = "resourcepacks/recolourful-containers-gui.pw.toml"
hash = "76ff5ae9354174e01cbf0f8eadbaabb13a7091805cfbc7c1901227c71bfe9017"
metafile = true

[[files]]
file = "resourcepacks/tras-fresh-player.pw.toml"
hash = "32fe0fe8941110f8fba07ce7768faa1797de6b28e961ab65b483c380fc0a365a"
metafile = true
