name = "Badly Optimized"
author = "Uranite"
version = "2.0.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc70475c7802e93bba8b3fc82413bea6a88de98a21186f2ed7a2137896c6de28"

[versions]
fabric = "0.18.0"
minecraft = "1.20.6"
