hash-format = "sha256"

[[files]]
file = "config/NoChatReports/NCR-Client.json"
hash = "32dc5f1d73b05e70f3fc5a18f58c5d81a095484a0f93a1da6d1883966ff4e296"

[[files]]
file = "config/badoptimizations.txt"
hash = "a47ef2a99eee3632074b8c2869e1ce3182f7348eaf916a2045e06b2a47e58cd4"

[[files]]
file = "config/cape-provider.json5"
hash = "6b65e1270f555a74560a10fa17bb6b7290e022f46dc02b29239b32a1b3d27b37"

[[files]]
file = "config/enhanced_bes.properties"
hash = "219204a2efc6d53ad8b3116db7392e039ba8e0ed5f45bc18562c9697bdf8f5c9"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "3817e94107bb1c7358beebb80b1810e822de38be430f855cf14828c38018e8e2"

[[files]]
file = "config/immediatelyfast.json"
hash = "eb455656c3e3e8effa1e9c085b96894b469aa545807e3f621dde74a1c3a0833f"

[[files]]
file = "config/iris.properties"
hash = "4b404c16b82563e05e0cc8dc1218eb6194b2aa4473f348ff0c0c7a8655d9b5ff"

[[files]]
file = "config/litematica.json"
hash = "68322256c1240f38496d80e3e6df017a936cec6d9d965b7f815a4966c5873f5d"

[[files]]
file = "config/malilib.json"
hash = "c7acba3f6019a96750b90508685939ab0801876a9d6f40475e9310eb05d620ed"

[[files]]
file = "config/modernfix-mixins.properties"
hash = "e46272cc1db3b1f8c7d6bdc0c89d0b2e336a8d30ad0081e645f76c427be3cbec"

[[files]]
file = "config/moreculling.toml"
hash = "47c90ca85fa6733e7b4fb652760b91506957ae19a830c02caa72d20df405819a"

[[files]]
file = "config/puzzle.json"
hash = "9ef4deb1dee36af524dd6c6664c9ae36934639c0384b232c1109d1fd92becba9"

[[files]]
file = "config/sodium-extra-options.json"
hash = "e3927c55ce0508a6328e373e1811191836fe56933f73d1fb320a1df21154081d"

[[files]]
file = "config/sodium-options.json"
hash = "5358a572a26d8008c6c49e00ab3a0fe65dd89761cb86a235496900b587b9526c"

[[files]]
file = "config/subtle_effects/entities.toml"
hash = "96911064afde34aadcea96b343e20fa8101ffd843306760558851145ba0dcd85"

[[files]]
file = "config/vmp.properties"
hash = "0d0549563aca08c87a22a9fd862cc6e7a9906f2d6fca84dcbfa7cbec14dff7e6"

[[files]]
file = "config/xaerominimap.txt"
hash = "8627b3553cbc1ae4e5556e7132991abc45d5a7b604f593e75f1389091278e0a5"

[[files]]
file = "config/xaeroplus.txt"
hash = "8b400926fa2c106000afe3609286259d69491bd725ca2dc7d0a27a3d9ea6dd08"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "f6ecd46f2cf0e9387fa45c31184f40d361efd70f5645bad8876b51764ca6fdf5"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "ff31791271197f8122fb52893e7e67d86ba038dd0e77e57227ef84de8f7e069e"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "17fc9c6cab5ae0ea6973440f143ad6ffa4e5d373749c80077b631dbbe4df3f3b"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1102440dd2533ba3a154419bb95ff1f81b858201eb0c44d2a2eea486c74e565a"
metafile = true

[[files]]
file = "mods/armor-stand-arms.pw.toml"
hash = "0da2620f9f2924df98e74928ed92f051b6250632656752429074ecbcad2ee808"
metafile = true

[[files]]
file = "mods/asyncparticles.pw.toml"
hash = "4f20967ee66eb96cbcfaa63bea9d3424ac45b7db414c9a491f31c86012f34fb5"
metafile = true

[[files]]
file = "mods/axolotl-buckets.pw.toml"
hash = "d0cd8ee363b3575642a53827025ceddc28c9a6cc344830d537fb39751cf2a299"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "be28a9ff89c60140b2983eb91089e77bec90bc5a0379c25472be01cb14dcbb97"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
hash = "7b87ea6e0623ada323e65fa0420e0827f6e88689898a0454376e460ad8cbc5dc"
metafile = true

[[files]]
file = "mods/bl4cks-sit.pw.toml"
hash = "b698ef315db976c1f3dea7a1a65fe9b41e6b5f7b84e59e3bd79a25185094ef32"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "83f893fc77eb4186677454bd38e3a7da78f657c943fe066929321edca29d1eda"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "c5833c66008b22b8cdcbc719300e34f9e29a14f5c67789c0498451448ab40296"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "941c3f358ef74f4fc99727e550106b8905d77cb4971321fd8ca4406e33b704a6"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "c899acdc322ab52800a6e305a16427297f411c1c39d97983be96e8b6a34e157c"
metafile = true

[[files]]
file = "mods/cave-dust.pw.toml"
hash = "be7918d29b7fc9f820b6574f3906c1d1decc0fd485d55db5f408429e02bf70b1"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "2dda36229536c02155b8bdc705598904b74b3e958e56bf7946785f59c3427a9b"
metafile = true

[[files]]
file = "mods/chatanimation.pw.toml"
hash = "a59ce679862d915b6a8bdfe207af78012214fb5a6952e0663eb07c98d7c88793"
metafile = true

[[files]]
file = "mods/cherished-worlds.pw.toml"
hash = "8f534cf725f8fc338c29453a25bbff94c5adba4f4b1815863f5d0f073b8f42e3"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
hash = "e5196147e561521c5a3ebaea601191e442d252cc8f0a7be8ba8db136f93c44fe"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "cde21d14fcaf9495f0f5b3d8fb298dd60cb12badc21a27414c25ebf11dfb3fe1"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "4f97764f3cb4c74f84afbe32cf8a1d2cefecda129c0f1441906562dcb8f2b8cb"
metafile = true

[[files]]
file = "mods/coolrain.pw.toml"
hash = "d21038ff74cc6f4b4b9682539f33b882b4423a55da3c79f40ce129818ad837c0"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
hash = "01e094e3599564ea056dc71f42cc10854609a5ffbb3f83415225a3bdcbf8680e"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "60eab6ec5f29fc035ece627513e61cdacebcba6a7f7c0406ce977c802832e865"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "3f8fb0012b658c3ed2dfcde1385aa6255ee46cd18b77975d68665aaf0ee2a94d"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
hash = "24d6c27315866a6dd672daef2f844b1b202aa173953824cb3586bed8667f3d5c"
metafile = true

[[files]]
file = "mods/dripsounds.pw.toml"
hash = "4e230e35117c08a4f63428b6b1d62b1e6d14542ccf91396dc4fbc98527c51db4"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
hash = "c03848ab316f8f8e07656e08c675541ce90f0ad729d5b31df336fe8f27a58b3f"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "b1f89407254a20cde6c60994a6315bd841b7f562669a1d29b436ec97463ff2ae"
metafile = true

[[files]]
file = "mods/elytra-trims.pw.toml"
hash = "f494105361f4e017cd4b304c49e76bd72951f8c63a7c2a6fd011749deb4a6140"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "9b4f807d450b801e1ebde79ea08c8ff85a12e5cd27636344dda2b238182a1a4f"
metafile = true

[[files]]
file = "mods/entity-pin-cushions.pw.toml"
hash = "98fc45453fdac86d361d4d16736983534d93f1c4006bcece0502070d259126d4"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "054628ed76bd95bde1dbb4343721f3fbed87c8ad798ce99fc74b1171c39b6400"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "7c9e1ab7c069568acfe6e5d2bad168ef66ff4840bebf09316099661e42f43b0b"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "6b0b4bf6142ff8a72758914307684881bd7b545884bb8049f8cf6442670ec8a3"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "446f8047ee9168b65fe9d4600f82cb915c7aa0d0f049a344177ba340a5b93a8a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "9fb4d588bd578e2f16a9605ff6303872130b36ccb0fdfff98bd7274da94f91b9"
metafile = true

[[files]]
file = "mods/forcecloseworldloadingscreen.pw.toml"
hash = "d80049f4f9438f229920965bfbd1354a23165747a1f84e9b39ab8333bce527c5"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "238b3ceb4214a682480ce00eefae5d34efa299ff6ff667e4b2f2ed503c6e76ee"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "518e512a141b3b331ecaafaf315a9636f9eadf211c0df39395109e8dbf588a54"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "d8cdb69801ff0ffdf8c9cf6834dd592ca79ce1da139d303f8d17a62afec1abe2"
metafile = true

[[files]]
file = "mods/horse-expert.pw.toml"
hash = "446b9d3a5a8755894a9b15c47a1bc838ba59cb93b0f5d7f2b60bfdb1ac7e7ba7"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "907ed71a8d572d5bc2a8f956b0b0d0fad37e1d5bdd48464041a76ef8fca79cb7"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "664035ab6b81584cc42c158d4246a0888e42e41a1ad66c2985694392fd192b86"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "5284f6d141a990f4ea021c12b851e07102f5cb22743cf7b33be6ad2eb4c8d3f5"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "894e5bf05eb42c2a6a2fc872b509135a47a39572abbd006528a4c79d962524f2"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "9236940eafe8e97819f093c3c77236ee47de3b7f97a17f3fcf31114034962611"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "2898959cae6f90183ad4c6e0384b4b7cc485ae0ef9474e7765a57d97a2542b05"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "10d2cb5f575d0c290549758cafe0e3b15acbca8c5163aa4209cbe4fb8fcb7de5"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
hash = "237f61291d7f6cbfe8bafd6fc22657000adc2b8de269061eb81b6eb21d3ea5d1"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "804bd885dd40336596175503d631ab7f529ad12e152872462b1c25f15b2f89bd"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "972db8c2fec6fb2f3545554062d4cd19364778e30d8f079221fe0d459efa8517"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "33b394f6cf1849a124b2021a56b29455e2fcb2c5a3a56901fe8ad0dbf3d4c6ee"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
hash = "f531a8ee70e9d78ee62a84e3fd18088070dcf8f2cee2384a8aabed16dbfafe6c"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "d9221689ffa47dcd27e6c0590ba7b3227f83d48a6e9592cd09e1835f143d793a"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "d12b136e07f6f83a1e199aabe430426d19702c9f69e55731092b5d5c2f3fb69f"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "b9651d06e56ad51c1cdcf4b03b6a34328b7dc941f263ff92b189ee26a47cc224"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d917697e84a95f857a447d26f94d93169a5a62176c93193cdf80c8d8bc1e280a"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "6be43ffc708ac329843aee99ededc692ecf6461ee8e409d373f55fc5494db5af"
metafile = true

[[files]]
file = "mods/naturally-trimmed.pw.toml"
hash = "8a4477de50fbb65bd59b6358ec6faf4f2c982e3746bdd8d0cd580eabf81a1cf0"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "f3c5cb21ff2e78c7e8cdbd14d1535e6edd464d5a436dbfa4e60b8ea91374674d"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "7d5af9f25bc04dd33ec6e55983f7c660d0802461ecad3b5a820dd05dfcef2f70"
metafile = true

[[files]]
file = "mods/nvidium-0.4.1-beta9-1.21-1.21.1.jar"
hash = "7cff31c04bf910dcb85eb4de06581d7a02219fd1d8ac9294b34fb3e9a56958e6"

[[files]]
file = "mods/optiboxes.pw.toml"
hash = "c3c0af49a34f2ea66faaf78b08f9b8858bbac60d5aca3b85542d45697bb53e36"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "6f45c3f2ec9005b18846088784d291f4dabcce7b569031fb44855845a33aa8f7"
metafile = true

[[files]]
file = "mods/particle-effects.pw.toml"
hash = "9d378d54412fbd27745dbf519ea7e323eaee5facf436ad18dfea5f3e7155b200"
metafile = true

[[files]]
file = "mods/particle-interactions.pw.toml"
hash = "6a085c05e1c4f0712bf68d60cd3ed4d658e87e6fd186caaf380015ece32eaf57"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "6e454809d22c0967ace0a59408260da91ce80757d00eaa4720f0496fcd1fddd1"
metafile = true

[[files]]
file = "mods/pickup-notifications.pw.toml"
hash = "d6de6e02902903a4f55f77ae9a50ae2cc0ea11f33366a7c6692de05992305a18"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "2e2c1b47b513663871e71c89a699c66ac9fcc97633f007ed064ce4410f220f5a"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "62df1cb449d5c6f8c5d670f14819a106a451e88102b8b066efeb73951f058d30"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "0bc4266f50288f9a9d78e84745b50bf6886e0ff69ba78561867e6e32d2292b09"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "dee709ea8dbbb9e75de4d53b1b9e1fd0e535abc0809c1f5aaadf783178cccf21"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "93dca70663db0eaedb6bd6fe8d934631724075be914faa5715d9f237b867ffe0"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "44a6662d6ac604b2173a8bc426a10c0d621c8ba99d37d1b72525c140c42cb358"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "55a727cabdd9d6e84fb0232b49d0dfa207751002e7f1f63b959baa35e2f29868"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "ceb180c764fa9c7c12c7e750cc7b726171277cb2b68e47370888c4ff4679a4ed"
metafile = true

[[files]]
file = "mods/serverpingerfixer.pw.toml"
hash = "480117bbfe84aa4d902cd1f45053ed4df0738f12daf163d83436e5a1ac2804e2"
metafile = true

[[files]]
file = "mods/smooth-scroll.pw.toml"
hash = "69d9366753ade6e5dbcbbac31372fae83d6b37b81a63a797a217aa69e97f2992"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "1af09f16a643df0f61f2c799e981aa0b8c109999f0784584a6eff9a81f1c00c1"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "f5d79572111f977729f99c58143e2296383cb16634f5b9805382b832e8e86300"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
hash = "1fa203fbf7578d4f6fc251b3529cf79935d7e4a573a281241de74e488be639b7"
metafile = true

[[files]]
file = "mods/subtle-effects.pw.toml"
hash = "ea42c8cd33e92216bac99e999fd9d2e1e037dd1a695ed5e7e05c640fd3ee35d8"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "ffa71e1ce188b71291daa8bb67e8094ff7d0ef695add362200591c28e75cf457"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "6c6b69bf2bca3b3a8420688391124aa90d24e235b98ee01097f03f0fbf22d9cb"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "da7ee99189ad35aac094919fe33cac647d98533b23c228f10d4811f08989e2b8"
metafile = true

[[files]]
file = "mods/text-formatting-everywhere.pw.toml"
hash = "7e08e4f76649a2fba00bb6eae7b59af18513c01140b50cd94299c70232c597c9"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
hash = "19faff688fb5bdd5e0151876da94b1ceb98aedaf411574f494497cef06f7fed9"
metafile = true

[[files]]
file = "mods/viafabricplus.pw.toml"
hash = "c9ffa90c6e4445ac75b9f6d6bfcf93c054133d1cc71e7e42ec6ec789dce731d1"
metafile = true

[[files]]
file = "mods/villager-names-serilum.pw.toml"
hash = "384337b9af46d36f7d45fbbd1e9ea5801704df31a0db000f862e16aac71c24a7"
metafile = true

[[files]]
file = "mods/visual-jukebox.pw.toml"
hash = "66fcd02ee8dcaeb20fa25333e5949fdd3c17a9db6e50d020550a4d8bebccb2f9"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "37c8746fe9057612cd4f21e1221760e8dd2f78ce6b38a237b0ac925de21541e0"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "39426bfeeab22ea17f94fd3904dd9b78f9a3c9b4ddcb732b734ddbfd0e3568af"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "99cc4bdfa44196b887c0b6ea48622f89a6a004866a9af47b929dabe5331e2605"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "33122c36e3a43deb6550a425ad01fa434e9964b2bbfd306743e021fb94a4de5c"
metafile = true

[[files]]
file = "mods/world-play-time.pw.toml"
hash = "2dc8224c90ea8cc20d8d497a16c679b0928d870c58ffe84100d8f4092184f4e4"
metafile = true

[[files]]
file = "mods/xaeroplus.pw.toml"
hash = "212e299ca8b0117216259fc6933e4a9c8158cf2931f86e0eb3d13436b6a9eba7"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "8f391603f2b1aaf63717c180e82635b7cd2d57617c02edac60f9d25244731df1"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "930c62a2d832d9b9dac1637a89265415007eba0033e84cbc1b9b80bd6f483554"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "345fc6586d50c4377ac413117d8ccdf30d2ed6169545225c28f19a26a51aa653"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "fb09f6357ae2e3dcfea36520efde6e9b761efffc63b4dfdec5e4b11011bac58c"
metafile = true

[[files]]
file = "options.txt"
hash = "952dfb991f549b9a77bd40368ec003221c6a0f2f364af5bcff2deb8a78073183"

[[files]]
file = "resourcepacks/3d-ladders.pw.toml"
hash = "41b824d57c58ed52a7c63b162e036e79a02cae78ce551b31423ccf2eb752b110"
metafile = true

[[files]]
file = "resourcepacks/better-lanterns.pw.toml"
hash = "17ea105b98d79a0be6ce20da3304f9ed1398c5d9d3ad24cea2c914a109ede78e"
metafile = true

[[files]]
file = "resourcepacks/chat-reporting-helper.pw.toml"
hash = "b33036850e44c6a79c3995027144a1758ca16e0f46c36bc068870575e2f4fe26"
metafile = true

[[files]]
file = "resourcepacks/drodis-blazes-x-fresh-animations.pw.toml"
hash = "df3860935e4d3a6aa0bd3a7aa1aa6e9d0703204db231a37f60f983bfe0ed05f7"
metafile = true

[[files]]
file = "resourcepacks/enchant-icons-countxd.pw.toml"
hash = "bb2b6a511327bc8782c7c12c6be81c11fa3fcb7fa4fd10d4093a5170862e1ad5"
metafile = true

[[files]]
file = "resourcepacks/enchanted-books-re-covered.pw.toml"
hash = "f02b95d21e78b75d1a1c93296e1dd90dc5d03439958fd1596cb77bbce864663f"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "b843c282f94af79a4970c91879eff4073932409aa045b722b48054bd4b2fd45d"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "bf6bf356ece200c132c604c1cdd981c8a7baf6a30ed05fa057fdfc0444df779d"
metafile = true

[[files]]
file = "resourcepacks/fresh-flower-pots.pw.toml"
hash = "6ea70716dbbdddf6bdbeb137208a38380159048813accecb225ca6d19ce37e97"
metafile = true

[[files]]
file = "resourcepacks/gentler-weather-sounds.pw.toml"
hash = "9164c7d742c4e3272081c48a9559b00a16c918ce7ed27857a252fc7db18d3cdd"
metafile = true

[[files]]
file = "resourcepacks/human-era-villagers-illagers.pw.toml"
hash = "c3a40eb78034c9c013928db9a02a814070d8041e9648c8bd7b5fefbd5f5ba9ef"
metafile = true

[[files]]
file = "resourcepacks/rays-3d-rails.pw.toml"
hash = "0e80f97855da0ee8b2cba02d4cc1f3c82f50bd1ec0772645cfd5dd5d6f4e9a86"
metafile = true

[[files]]
file = "resourcepacks/recolourful-containers-gui.pw.toml"
hash = "76ff5ae9354174e01cbf0f8eadbaabb13a7091805cfbc7c1901227c71bfe9017"
metafile = true

[[files]]
file = "resourcepacks/shaderpanorama1216.pw.toml"
hash = "44fb3671f9763b0521f73f25571be60c25bbc8be9ef36674a9d3c166ffa77038"
metafile = true

[[files]]
file = "resourcepacks/theones-eating-animation-pack.pw.toml"
hash = "fdd57898bc0a95edd94cffb22fd9babb3d56a877156c3a2d6887b74404e1b2c7"
metafile = true

[[files]]
file = "resourcepacks/tras-fresh-player.pw.toml"
hash = "32fe0fe8941110f8fba07ce7768faa1797de6b28e961ab65b483c380fc0a365a"
metafile = true

[[files]]
file = "resourcepacks/visual-armor-trims.pw.toml"
hash = "d88dacad6b166ce9766867b4224aa175e55cfd75caad6a77f698abee8fec9d11"
metafile = true
