name = "Badly Optimized"
author = "Uranite"
version = "2.0.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fb11a197b8f27265eea1f07bced372bf1ce90ba1b8c43fc0938a297436d5b43"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
