name = "Badly Optimized"
author = "Uranite"
version = "2.0.0+1.21.10.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1831727803b6ba0feaef3c649011c8c99b6aaebee074a768f1eb6676202315a8"

[versions]
fabric = "0.18.0"
minecraft = "1.21.10"
