name = "Badly Optimized"
author = "Uranite"
version = "2.0.0+1.21.10.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c77314f143846e6b734b3ef192ff240622299947ae15484ea4778929c7e9202"

[versions]
fabric = "0.18.0"
minecraft = "1.21.10"
