name = "Badly Optimized"
author = "Uranite"
version = "2.0.0+1.21.8.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6fbadc993acd9943fd7c8a0c1db99ed442295433ce75bc5ed527d7396fcaf82"

[versions]
fabric = "0.18.1"
minecraft = "1.21.8"
