name = "Badly Optimized"
author = "Uranite"
version = "2.0.0+1.21.8.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "444c605c1f94cd185a1012fc2151f9eccf8fa39e4d24f5180e9d67f5ca987343"

[versions]
fabric = "0.18.1"
minecraft = "1.21.8"
